# Generated by Django 5.1.3 on 2025-01-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_name_department_dept_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='dept_name',
            new_name='dept_no',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dept',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='employee',
            name='bonus',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.FloatField(),
        ),
    ]
