# Generated by Django 5.1.3 on 2025-04-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_employee_role_employee_job_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_role',
            field=models.CharField(max_length=100),
        ),
    ]
