# Generated by Django 5.1.3 on 2025-01-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_department_employee_dept_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
